web/Web/config/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
import notifications.urls

from config.logger import LoggerView

urlpatterns = [
    path('', include('web.core.urls', namespace='core')),
    path('about/', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    path('users/', include('web.users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),

    # Notifications
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

    # Custom urls includes go here
    path('discovery/', include('web.CAL.urls', namespace='CAL')),
    path('search/', include('web.search.urls', namespace='search')),
    path('topic/', include('web.topic.urls', namespace='topic')),
    path('judgment/', include('web.judgment.urls', namespace='judgment')),
    path('review/', include('web.review.urls', namespace='review')),

    # Logger
    path(r'logger/', LoggerView.as_view(), name='logger'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

web/Web/web/core/urls.py
from django.urls import path

from web.core import views
from web.core import practice_views

app_name = "core"

urlpatterns = [
    path('', views.Home.as_view(),
         name='home'),
    path('sessions/', views.SessionListView.as_view(),
         name='sessions'),

    # Practice views
    path('practice/', practice_views.PracticeView.as_view(),
         name='practice'),
    path('practice_complete/', practice_views.PracticeCompleteView.as_view(),
         name='practice_complete'),

    # Ajax views
    path('get_single_doc/', views.GetDocAJAXView.as_view(),
         name='get_single_doc'),

    path('get_session_details/', views.SessionDetailsAJAXView.as_view(),
         name='get_session_details'),
    path('share_session_view/', views.SessionShareView.as_view(),
         name='share_session'),

    path('update_session_timer/', views.update_remote_session_timer, name='update_session_timer'),
    path('update_task_time/', views.update_task_time, name='update_task_time'),
]

web/Web/web/judgment/urls.py
from django.urls import path
from django.urls import re_path

from web.judgment import views

app_name = "judgment"

urlpatterns = [

    path('view/', views.JudgmentsView.as_view(),
         name='view'),

    # Ajax views
    path('post_judgment/', views.JudgmentAJAXView.as_view(),
         name='post_judgment'),
    path('post_nojudgment/', views.NoJudgmentAJAXView.as_view(),
         name='post_nojudgment'),
    re_path(r'^get_latest/(?P<number_of_docs_to_show>\d+)/$',
            views.GetLatestAJAXView.as_view(),
            name='get_latest'),
    path('get_all/', views.GetAllAJAXView.as_view(),
         name='get_all'),
]

web/Web/web/core/views.py
from config.settings.base import TIME_ZONE
import json
import logging

from braces import views
from django.contrib import messages
from django.db.models import Case
from django.db.models import Count
from django.db.models import When
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import View
from django.views import generic
from interfaces.DocumentSnippetEngine import functions as DocEngine

import pytz
from web.core.forms import ShareSessionForm, PreTaskQuestionnaireForm
from web.core.mixin import RetrievalMethodPermissionMixin
from web.core.models import Session
from web.core.models import SharedSession
from web.core.session_utils import activate_session_submit_form, submit_task_questionnaire_form
from web.core.session_utils import delete_session_submit_form
from web.core.session_utils import revoke_shared_session_submit_form
from web.core.session_utils import share_session_submit_form
from web.core.session_utils import submit_new_predefined_topic_session_form
from web.core.session_utils import submit_new_session_form
from web.judgment.models import Judgment

logger = logging.getLogger(__name__)



def update_remote_session_timer(request):
    if request.user.is_authenticated:
        if request.user.current_session:
            request.user.current_session.update_session_timer()
    return JsonResponse({"message": "Session updated."})


def update_task_time(request):
    if request.user.is_authenticated:
        if request.user.current_session:
            time_worked = request.user.current_session.timespent
    return JsonResponse({"task_time": f'{int(time_worked // 60)} minutes and'
                                      f' {int(time_worked % 60)} seconds'})


class Home(views.LoginRequiredMixin, generic.TemplateView):
    template_name = 'core/home.html'

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)

        # COUNTERS
        counters = Judgment.objects.filter(user=self.request.user,
                                           source="CAL",
                                           session=self.request.user.current_session).aggregate(
            total_highlyRelevant=Count(Case(When(relevance=2, then=1))),
            total_relevant=Count(Case(When(relevance=1, then=1))),
            total_nonrelevant=Count(Case(When(relevance=0, then=1)))
        )

        context["total_highlyRelevant_CAL"] = counters["total_highlyRelevant"]
        context["total_nonrelevant_CAL"] = counters["total_nonrelevant"]
        context["total_relevant_CAL"] = counters["total_relevant"]

        counters = Judgment.objects.filter(user=self.request.user,
                                           source__contains="search",
                                           session=self.request.user.current_session).aggregate(
            total_highlyRelevant=Count(Case(When(relevance=2, then=1))),
            total_relevant=Count(Case(When(relevance=1, then=1))),
            total_nonrelevant=Count(Case(When(relevance=0, then=1)))
        )

        context["total_highlyRelevant_search"] = counters["total_highlyRelevant"]
        context["total_nonrelevant_search"] = counters["total_nonrelevant"]
        context["total_relevant_search"] = counters["total_relevant"]

        collaborators = []
        shared_with_objs = SharedSession.objects.filter(
            refers_to=self.request.user.current_session
        )
        if self.request.user.current_session:
            collaborators.append(self.request.user.current_session.username)
        for shared_obj in shared_with_objs:
            collaborators.append(shared_obj.shared_with)
        context["collaborators"] = collaborators

        return context

    def get(self, request, *args, **kwargs):
        return super(Home, self).get(self, request, *args, **kwargs)

    def post(self, request, *args, **kwargs):

        if "submit-session-predefine-topic-form" in request.POST:
            submit_new_predefined_topic_session_form(request)
        elif "submit-post-experiment-questionnaire-form" in request.POST:
            submit_task_questionnaire_form(request, 'post_experiment')
        elif "submit-post-task-questionnaire-form" in request.POST:
            submit_task_questionnaire_form(request, 'post_task')
        elif "submit-pre-task-questionnaire-form" in request.POST:
            submit_task_questionnaire_form(request, 'pre_task')
        elif "submit-session-form" in request.POST:
            submit_new_session_form(request)
        elif request.POST.get("share_sessionid"):
            share_session_submit_form(request)
        elif request.POST.get("revoke_sessionid"):
            revoke_shared_session_submit_form(request)
        else:
            messages.add_message(request,
                                 messages.ERROR,
                                 'Ops. Something went wrong.')
        return HttpResponseRedirect(reverse_lazy('core:home'))


class SessionListView(views.LoginRequiredMixin, generic.TemplateView):
    template_name = 'core/sessions.html'

    def get_context_data(self, **kwargs):
        context = super(SessionListView, self).get_context_data(**kwargs)
        context["share_session_form"] = ShareSessionForm(user=self.request.user)

        user_sessions_queryset = Session.objects.filter(username=self.request.user).order_by("created_at")
        sessions = []
        for session_obj in user_sessions_queryset:
            session_info = {"session_obj": session_obj,
                            "created_at": timezone.localtime(session_obj.created_at,
                                                             pytz.timezone(TIME_ZONE))
                            }
            sessions.append(session_info)
        context["sessions"] = sessions

        shared_sessions = []
        shared_sessions_queryset = SharedSession.objects.filter(shared_with=self.request.user).order_by('created_at')
        for shared_session_obj in shared_sessions_queryset:

            shared_sessions.append({
                "shared_session_obj": shared_session_obj,
                "created_at": timezone.localtime(shared_session_obj.created_at,
                                                 pytz.timezone(TIME_ZONE))
            })
        context["shared_sessions"] = shared_sessions
        return context

    def get(self, request, *args, **kwargs):
        return super(SessionListView, self).get(self, request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if request.POST.get("activate_sessionid"):
            if activate_session_submit_form(request):
                HttpResponseRedirect(reverse_lazy('core:home'))
        elif request.POST.get("delete_sessionid"):
            delete_session_submit_form(request)
        elif request.POST.get("share_sessionid"):
            share_session_submit_form(request)
        elif request.POST.get("revoke_sessionid"):
            revoke_shared_session_submit_form(request)

        return HttpResponseRedirect(reverse_lazy('core:sessions'))


class SessionDetailsAJAXView(views.CsrfExemptMixin, views.LoginRequiredMixin,
                             views.JsonRequestResponseMixin,
                             views.AjaxResponseMixin, generic.View):

    require_json = False

    def render_timeout_request_response(self, error_dict=None):
        if error_dict is None:
            error_dict = self.error_response_dict
        json_context = json.dumps(
            error_dict,
            cls=self.json_encoder_class,
            **self.get_json_dumps_kwargs()
        ).encode('utf-8')
        return HttpResponse(json_context, content_type=self.get_content_type(), status=502)

    def get_ajax(self, request, *args, **kwargs):
        session_id = request.GET.get('uuid')
        is_shared_session = request.GET.get('is_shared_session', False)
        is_shared_session = is_shared_session == "true"

        if not session_id:
            return JsonResponse({"message": "Ops! Session not found."}, status=404)
        session = {
            "uuid": session_id,
        }

        if is_shared_session:
            try:
                shared_session_obj = SharedSession.objects.get(uuid=session_id, shared_with=self.request.user)
                session_obj = shared_session_obj.refers_to
                session['uuid'] = session_obj.uuid
                shared_with_queryset_values = []
                session["owner"] = False
            except SharedSession.DoesNotExist:
                return JsonResponse({"message": "Ops! Session not found."}, status=404)
        else:
            try:
                session_obj = Session.objects.get(username=self.request.user, uuid=session_id)
                shared_with_queryset = SharedSession.objects.filter(
                    refers_to__uuid=session_id,
                    creator=self.request.user
                )
                shared_with_queryset_values = []
                for shared_session_obj in shared_with_queryset:
                    shared_with_queryset_values.append({
                        "uuid": shared_session_obj.uuid,
                        "shared_by": shared_session_obj.creator.username,
                        "shared_with": shared_session_obj.shared_with.username,
                        "shared_on": timezone.localtime(shared_session_obj.created_at,
                                                             pytz.timezone(TIME_ZONE)),
                        "disallow_search": shared_session_obj.disallow_search,
                        "disallow_CAL": shared_session_obj.disallow_CAL,
                    })
                session["owner"] = True
            except Session.DoesNotExist:
                return JsonResponse({"message": "Ops! Session not found."}, status=404)

web/Web/web/core/templates/core/home.html
{% extends 'core/home_base.html' %}
{% block pagetitle %}Home{% endblock %}
{% block home-nav-current-session-extra-class %}border-bottom{% endblock %}

{% block home-main %}
  <div class="col-md-8">
    <div class="card mt-4 border-0">
      <div class="card-block">
        {% if request.user.current_session %}
          {% if experiment_completed and form_to_show == 'none' %}
            <div class="alert alert-success" role="alert">
              <h4 class="alert-heading">Experiment Completed!</h4>
              <p>Congratulations! You have completed all the tasks. Please contact
                amanaam@uwaterloo.ca regarding any questions or concerns. We will reach out
                to you for your compensation. Thank you for your participation!</p>
              .</p>
            </div>
          {% elif form_to_show == 'post_experiment' %}
            <p class="mt-4">You have completed all the tasks. Please complete the post-experiment
              questionnaire.</p>
            <button type="button" class="btn btn-primary" data-toggle="modal"
                    data-target="#postExperimentModal">
              Post Experiment Questionnaire
            </button>
          {% else %}
            <div class="ml-auto">
            <h3>
              {{ request.user.current_session.label|default_if_none:"Task" }}
            </h3>
              <p>
                Please carefully read and understand the topic below before you start the task. For
                this task, you will have the following tools at your disposal:
              </p>
              <ul>
                {% if not request.user.current_session.disable_search %}
                  <li class="pb-2"><em class="text-primary">Search:</em> Works like a regular
                    search engine. You can use it to search for documents relevant to the given
                    topic.
                  </li>
                {% endif %}
                {% if not request.user.current_session.integrated_cal %}
                  <li><em class="text-primary">Discovery:</em> Machine learning model that
                    recommends relevant documents based on your document judgments. The model
                    understands your notion of relevance through the documents you have judged
                    and thus, gets better with time.
                    {% if not request.user.current_session.disable_search %} Hence, it is
                      recommended
                      that you use search to find a few documents before switching to Discovery.
                    {% endif %}
                    <em class="text-danger bold" style="font-style: normal">
                      {% if request.user.current_session.nudge_to_cal %}Important note: The
                        CAL/Discovery model
                        will be disabled for this task until you have found at least 5 relevant
                        documents. {% endif %}</em>
                  </li>
                {% else %}
                  <li><em class="text-primary">Discovery:</em> Machine learning model that
                    recommends relevant documents based on your document judgments. The model
                    understands your notion of relevance through the documents you have judged
                    and thus gets better with time. Thus, it is recommended that you use search
                    to find a few documents before using to Discovery.
                    <em class="text-danger bold" style="font-style: normal">Important note: Once you
                      search for a query, the CAL/Discovery model will appear at the top of the
                      page alongside the search results.
                      {% if request.user.current_session.nudge_to_cal %} The CAL/Discovery model
                        will be disabled for this task until you have found at least 5 relevant
                        documents. {% endif %}</em>
                  </li>
                {% endif %}
              </ul>
              <h6 class="mt-4 text-primary">
                Topic Details
                <a class="badge float-right text-muted shadow-none session-details"
                   data-toggle="modal" data-target="#sessionModal" href="#"
                   data-is-shared-session={% if not current_session_owner %}"true"{% else %}
                     "false"{% endif %}
                data-session-id={% if user.current_session.username != user %}"
                {{ activated_shared_session.uuid }}"{% else %}"{{ user.current_session.uuid }}
                "{% endif %}
                data-session-title="{{ user.current_session.topic.title }}"
                ><i class="fas fa-info-circle"></i> Show more</a>
              </h6>
              <div class="list-group mt-4 pb-4">
                <div class=" border-0 p-0">

                  <div class="d-flex w-100 justify-content-between">

                    <p class="mb-2">Topic title: {{ user.current_session.topic.title }}</p>
                    {% if user.current_session.topic.number %}
                      <small>#{{ user.current_session.topic.number }}</small>{% endif %}
                  </div>
                  {% if user.current_session.topic.description %}<p class="mb-1">Topic
                    Description: {{ user.current_session.topic.description }}
                      {{ user.current_session.topic.narrative|default_if_none:"" }}
                  </p>
                  {% endif %}
                </div>
              </div>

              {% if form_to_show == 'pre_task' %}
                <button type="button" class="btn btn-primary" data-toggle="modal"
                        data-target="#preTaskModal">
                  Pre Task Questionnaire
                </button>
              {% endif %}
              {% if form_to_show == 'post_task' %}
                <p class="mt-4">You have completed your current task. Please complete the post
                  task questionnaire to continue to the next task.</p>
                <button type="button" class="btn btn-primary" data-toggle="modal"
                        data-target="#postTaskModal">
                  Post Task Questionnaire
                </button>
              {% endif %}




              {% if current_session_owner %}
                {#      <h6 class="mt-4 text-primary">#}
                {#        Manage session#}
                {#      </h6>#}
              {% endif %}

            </div>
          {% endif %}
        {% else %}
          {% include 'cards/sessions/no_session_create_card.html' %}
        {% endif %}
      </div>
    </div>
  </div>

  <div class="card-block mt-4 border-0 col-md-8 m-3">
    {% if request.user.current_session %}
      {% include 'cards/judgments_table_card.html' %}

    {% endif %}
  </div>
  {% include 'modals/pre_task_modal.html' %}
  {% include 'modals/post_task_modal.html' %}
  {% include 'modals/post_experiment_modal.html' %}
{% endblock %}

web/Web/web/core/templates/core/home_base.html
{% extends "base.html" %}
{% load i18n has_group crispy_forms_tags static %}

{% block extra_head %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.js" type="application/javascript"></script>
{% endblock %}

{% block main %}
<div class="row border-bottom">
  <div class="offset-0 offset-sm-3 col-12 col-md-7 mt-0 mt-sm-2">
    <nav class="nav">
        {% block home-nav %}
        <div class="d-flex home-nav">
          <a class="nav-link mx-4 px-2 py-3 text-muted {% block home-nav-current-session-extra-class %}{% endblock %}" href="{% url 'core:home' %}">Current Session</a>
          {% if request.user.current_session %}
          <a class="nav-link mx-4 px-2 py-3 text-muted {% block home-nav-judgments-extra-class %}{% endblock %}" href="{% url 'judgment:view' %}">Judgments</a>
          {% endif %}
        </div>
        {% endblock %}
    </nav>
  </div>
</div>

<div class="row">
  <div class="col-md-3 d-none d-sm-block" style="margin-top: -4rem;">
    <div class="card mx-3 mb-2">
        <div class="card-block">
          <div class="center-text mb-3">
            <script>createIdenticonImage('{{ user }}', 260, 260, "img-fluid")</script>
          </div>
          <h4 class="mb-0">{{ user }}</h4>
        </div>
    </div>

{#    <div class="card mx-3 mb-2 border-0">#}
{#        <div class="card-block pb-3 border-bottom">#}
{#          <h6>User information</h6>#}
{#        </div>#}
{#    </div>#}


  </div>
  <div class="col-md-9">
    {% block home-main %}

    {% endblock %}
  </div>

</div>

{% endblock %}

{% block extra_scripts %}
<script>
// This is to update progrss. Not needed at the moment.
function percentageToDegrees(percentage) { return percentage / 100 * 360; }
$(".progress").each(function() {

  var value = $(this).attr('data-value');
  var left = $(this).find('.progress-left .progress-bar');
  var right = $(this).find('.progress-right .progress-bar');

  if (value > 0) {
    if (value <= 50) {
      right.css('transform', 'rotate(' + percentageToDegrees(value) + 'deg)')
    } else {
      right.css('transform', 'rotate(180deg)')
      left.css('transform', 'rotate(' + percentageToDegrees(value - 50) + 'deg)')
    }
  }

})

</script>

{% endblock %}

web/Web/web/core/templates/core/sessions.backup.html
{% extends "base.html" %}
{% block pagetitle %}Sessions{% endblock %}

{% block main %}
<div class="row">

  <div class="col-sm-12 col-md-4">
    <div class="card border-0 sticky-top" style="top: 73px; z-index: 0;">
      <div class="card-block">
        {% include 'cards/sessions/current_session_card.html' %}
      </div>
    </div>
  </div>

  {% if sessions %}
  <div class="col-sm-12 {% if shared_sessions %}col-md-4{% else %}col-md-8{% endif %}">
    <div class="card border-0">
      <div class="card-block">
        {% include 'cards/sessions/list_sessions_card.html' %}
      </div>
      <!-- Share session modal is included in base /-->
    </div>
  </div>
  {% endif %}

  {% if shared_sessions %}
  <div class="col-sm-12 {% if sessions %}col-md-4{% else %}col-md-8{% endif %}">
    <div class="card border-0">
      <div class="card-block">
        {% include 'cards/sessions/shared_sessions_list.html' %}
      </div>
    </div>
  </div>
  {% endif %}

  {% if sessions or shared_sessions %}
  <!-- Session details modal is included in base /-->
  <!-- Delete session modal -->
  {% include 'modals/delete_session_modal.html' %}
  {% endif %}

</div>
{% endblock %}

{% block extra_scripts %}

<script>
$(document).on("click", ".delete-modal", function () {
     var session_title = $(this).data('session-title');
     var session_id = $(this).data('session-id');
     $("#deleteSessionModalTitle").html( session_title );
     $("#deleteSessionModalDeleteButton").val( session_id );

     return false;
});

$(document).on("click", ".share-modal", function () {
     var session_title = $(this).data('session-title');
     var session_id = $(this).data('session-id');
     $("#shareSessionModalTitle").html( session_title );
     $("#shareSessionModalShareButton").val( session_id );

     return false;
});

function templateSharedToUser(shared_by, shared_with, shared_on, shared_session_uuid){
  let filledTemplate = `
  <div class="row mb-4 flex-row">
    <div class="col-6 border-0">
      <h6 class="text-truncate text-secondary">${shared_with}</h6>
      <p class="text-muted m-0" style="font-size: 65%;">Shared by ${shared_by} on ${shared_on}</p>
    </div>
    <div class="col align-self-center text-right">
      <button type="submit"
              data-session-id="${shared_session_uuid}"
              name="revoke_sessionid"
              value="${shared_session_uuid}"
              class="btn btn-sm btn-outline-danger">Revoke
      </button>
    </div>
  </div>
  `
  return filledTemplate;
}

$(document).on("click", ".session-details", function () {
     var session_title = $(this).data('session-title');
     var session_id = $(this).data('session-id');
     var is_shared_session = $(this).data('is-shared-session')

     $("#sessionModalTitle").html( session_title );

     $("#sessionModalSpinner").removeClass("d-none");
     $(".sessionModalDetails").addClass("d-none");
     $("#sessionModalError").addClass("d-none");
     $("#sessionDetailsTabs").addClass("d-none");

     // fetch session details
      $.ajax({
        url: '{% url 'core:get_session_details' %}?uuid=' +session_id +'&is_shared_session=' + is_shared_session,
        method: 'GET',
        success: function (result) {

          let session = result
          // session["total_highlyRelevant"]
          // session["total_nonrelevant"]
          // session["total_relevant"]
          // session["total_judged"]
          let owner = session['owner']
          let shared_with_obj = session['shared_with']
          let title = session['topic_title']
          let number = session['topic_number']
          let show_full_document_content = session['show_full_document_content']
          let effort = session['effort']
          if (effort <= 0){
            effort = "No max";
          }

          if (!owner){
            $("#sessionDetailsTabs").addClass("d-none");
          }else{
            $("#sessionDetailsTabs").removeClass("d-none");
            // Update shared with list
            $("#sessionSharedWithList").html("");
            for (let i = 0; i < shared_with_obj.length; i++){
              const shared_with_obj_i = shared_with_obj[i];
              $("#sessionSharedWithList").append(templateSharedToUser(
                      shared_with_obj_i["shared_by"],
                      shared_with_obj_i["shared_with"],
                      shared_with_obj_i["shared_on"],
                      shared_with_obj_i["uuid"],
              ))
            }
          }


          $("#session_created_at").html(session['created_at']);
          $("#session_description").html(session['topic_description']);
          $("#session_narrative").html(session['topic_narrative']);
          $("#session_seed_query").html(session['topic_seed_query']);
          $("#session_strategy").html(session['strategy']);
          $("#session_effort").html(effort);


          // Update piechart
          var ctx = document.getElementById("piechart");
          var data = {
                  labels: [
                      "Highly relevant",
                      "Relevant",
                      "Non relevant"
                  ],
                  datasets: [
                      {
                          data: [
                              session["total_highlyRelevant"],
                              session["total_relevant"],
                              session["total_nonrelevant"]],
                          backgroundColor: [
                              "#5cb85c",
                              "#f0ad4e",
                              "#d9534f"
                          ],
                          hoverBackgroundColor: [
                              "#5cb85c",
                              "#f0ad4e",
                              "#d9534f"
                          ]
                      }]
              };
          var myPieChart = new Chart(ctx, {
                  type: 'pie',
                  data: data,
                  options: {
                      legend: {
                          display: true,
                          position: 'right'
                      }
                  }
              });


          $("#sessionModalSpinner").addClass("d-none");
          $(".sessionModalDetails").removeClass("d-none");

        },
        error: function (result) {
            let message = result["responseJSON"]["message"]
            $("#sessionModalError").removeClass("d-none");
            $("#sessionModalError").html(message);
            $("#sessionModalSpinner").addClass("d-none");
        }
      });


     return false;
});

$('#sessionModal').on('hidden.bs.modal', function (e) {
  // reset active tab once modal is closed.
  $('#detailsTab').tab('show')
})

</script>
{% endblock %}