web/Web/config/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
import notifications.urls

from config.logger import LoggerView

urlpatterns = [
    path('', include('web.core.urls', namespace='core')),
    path('about/', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    path('users/', include('web.users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),

    # Notifications
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

    # Custom urls includes go here
    path('discovery/', include('web.CAL.urls', namespace='CAL')),
    path('search/', include('web.search.urls', namespace='search')),
    path('topic/', include('web.topic.urls', namespace='topic')),
    path('judgment/', include('web.judgment.urls', namespace='judgment')),
    path('review/', include('web.review.urls', namespace='review')),

    # Logger
    path(r'logger/', LoggerView.as_view(), name='logger'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

web/Web/web/core/urls.py
from django.urls import path

from web.core import views
from web.core import practice_views

app_name = "core"

urlpatterns = [
    path('', views.Home.as_view(),
         name='home'),
    path('sessions/', views.SessionListView.as_view(),
         name='sessions'),

    # Practice views
    path('practice/', practice_views.PracticeView.as_view(),
         name='practice'),
    path('practice_complete/', practice_views.PracticeCompleteView.as_view(),
         name='practice_complete'),

    # Ajax views
    path('get_single_doc/', views.GetDocAJAXView.as_view(),
         name='get_single_doc'),

    path('get_session_details/', views.SessionDetailsAJAXView.as_view(),
         name='get_session_details'),
    path('share_session_view/', views.SessionShareView.as_view(),
         name='share_session'),

    path('update_session_timer/', views.update_remote_session_timer, name='update_session_timer'),
    path('update_task_time/', views.update_task_time, name='update_task_time'),
]

web/Web/web/templates/modals/additional_judging_criteria_modal.html
<div class="modal" id="additionalJudgingCriteriaModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-primary">Additional Judging Criteria</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% for criteria in additional_judging_criteria %}
        <h6 class="text-secondary">{{ criteria.name }}</h6>

          {% if criteria.description %}
            <p class="text-muted">{{ criteria.description }}</p>
          {% else %}
          <div class="alert alert-light" role="alert">
            <div class="d-flex flex-row">
              <h5 class="mb-0 -items-center align-self-center pr-3"><i class="fas fa-info-circle"></i></h5>
              <span class="align-self-center">No information is provided for "{{ criteria.name }}".</span>
            </div>
          </div>
          {% endif %}

        {% endfor %}

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

web/Web/web/templates/modals/collaboration_modal.html
<div class="modal" id="collaborationModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-primary">Collaboration Bot</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>The suggester bot is powered by different AI models constantly trying to find relevant documents
          to increase the efficiency of your retrieval process.</p>

        <p class="text-muted small m-0">Note: the tools uses multiple AI methods and may take some time to complete.</p>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

web/Web/web/templates/modals/create_session_modal.html
{% load crispy_forms_tags %}

<div class="modal" id="createSessionModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header pb-0">
        <div class="modal-title text-primary d-flex flex-grow-1 ">
          <div class="d-flex flex-column flex-grow-1 ">
          <h5 class="text-primary">Create session</h5>
          <h6 class="text-muted">Creating sessions helps you organize your retrieval effort</h6>
          </div>

          <div class="d-flex align-items-center flex-grow-1 ">
            <ul class="nav nav-pills nav-justified flex-column flex-md-row" role="tablist">
              <li class="nav-item align-self-center">
                <a class="nav-link active" data-toggle="pill" href="#pills-custom-topic" role="tab">Custom</a>
              </li>
              <li class="nav-item align-self-center">
                <a class="nav-link" data-toggle="pill" href="#pills-predefined-topic" role="tab">Pre-defined</a>
              </li>
            </ul>
          </div>

        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="tab-content">
          <!-- Custom topic tab -->
          <div class="tab-pane fade active show" id="pills-custom-topic" role="tabpanel">
            <div class="row">
              <div class="col-md-12 mt-3">
                    <form method="POST" action="{% url 'core:home' %} " enctype="multipart/form-data">
                    {% csrf_token %}
                    {% crispy form_custom %}
                    </form>
              </div>
            </div>
          </div>

          <!-- Predefined topic tab -->
          <div class="tab-pane fade" id="pills-predefined-topic" role="tabpanel">
            <div class="row">
              <div class="col-md-12 mt-3">
                  <form method="POST" action="{% url 'core:home' %}">
                  {% csrf_token %}
                  {% crispy form_predefined %}
                  </form>
               </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">
          Cancel
        </button>
      </div>
    </div>
  </div>
</div>

web/Web/web/templates/modals/delete_session_modal.html
<div class="modal" id="deleteSessionModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-primary" id="deleteSessionModalTitle"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this session?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">
          Close
        </button>
        <form action="" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger" name="delete_sessionid"
                  value="" id="deleteSessionModalDeleteButton">Delete
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

web/Web/web/templates/modals/help_modal.html
<div class="modal" id="helpModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-primary">{%block help-modal-title%}How to use Gathera{%endblock%}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {%block help-modal-body%}<p>Gathera is a system for efficient high-recall retrieval that allows retrieving and assessing relevant documents and provides high data processing performance with a user-friendly document assessment interface.</p>
        <p>There are two retrieval components in Gathera.</p>
        <p><strong class="text-primary">Search:</strong> the search component allows you to search for documents using a search engine. Judgments made in the search component are used to train the Discovery model.</p>
        <p><strong class="text-primary">Discovery:</strong> Discovery is an iterative feedback process that uses a machine learning classifier to train on relevance judgments made by the user.
         The Discovery interface presents the user with top scoring unjudged documents in the collection. After each iteration of judging and re-training, the learning model improves and returns the next most likely relevant documents to judge.
        </p>
        <p class="text-muted small m-0">To learn more about Gathera, visit the <a href="http://www.gathera.ai">Gathera's website.</a></p>{%endblock%}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

web/Web/web/templates/modals/idle_modal.html
<div class="modal" id="IdleModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-primary">Are you still working?</h5>
      </div>
      <div class="modal-body">
        <p>You have not made any judgment for some time now. Are you still working? If yes please
          press "Okay" button to continue working.
        </p>
      </div>
      <div class="modal-footer">
        <button id="modal-ok" type="button" class="btn btn-outline-secondary"
                data-dismiss="modal">Okay</button>
      </div>
    </div>
  </div>
</div>

web/Web/web/templates/modals/keyboard_shortcuts_modal.html
<div class="modal" id="keyboardShortcutsModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-primary">Keyboard Shortcuts</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="alert alert-warning" role="alert">
          <div class="d-flex flex-row">
            <h5 class="mb-0 -items-center align-self-center pr-3"><i class="fas fa-info-circle"></i></h5>
            <span class="align-self-center">Keyboard shortcuts are not set.</span>
          </div>
        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

web/Web/web/templates/modals/post_task_modal.html
{% load crispy_forms_tags %}

<div class="modal" id="postTaskModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header pb-0">
        <div class="modal-title text-primary d-flex flex-grow-1 ">
          <div class="d-flex flex-column flex-grow-1 ">
          <h5 class="text-primary">Post Task Questionnaire</h5>
          </div>

        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <div class="row">
            <div class="col-md-12 mt-3">
              <div class="list-group mt-4 pb-4">
                    <div class=" border-0 p-0">

                        <div class="d-flex w-100 justify-content-between">

                          <p class="mb-2">Topic title: {{ user.current_session.topic.title }}</p>
                          {% if user.current_session.topic.number %}<small>#{{ user.current_session.topic.number }}</small>{% endif %}
                        </div>
                        {% if user.current_session.topic.description %}<p class="mb-1">Topic
                          Description: {{ user.current_session.topic.description }}
                          {{ user.current_session.topic.narrative|default_if_none:"" }}</p>{% endif %}
                    </div>
                </div>
                <form method="POST" action="{% url 'core:home' %} " enctype="multipart/form-data">
                  {% csrf_token %}
                  {% crispy form_post_task %}
                </form>
            </div>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">
          Cancel
        </button>
      </div>
    </div>
  </div>
</div>

web/Web/web/templates/modals/pre_task_modal.html
{% load crispy_forms_tags %}

<div class="modal" id="preTaskModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header pb-0">
        <div class="modal-title text-primary d-flex flex-grow-1 ">
          <div class="d-flex flex-column flex-grow-1 ">
          <h5 class="text-primary">Pre Task Questionnaire</h5>
          </div>

        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <div class="row">
            <div class="col-md-12 mt-3">
                <div class="list-group mt-4 pb-4">
                    <div class=" border-0 p-0">

                        <div class="d-flex w-100 justify-content-between">

                          <p class="mb-2">Topic title: {{ user.current_session.topic.title }}</p>
                          {% if user.current_session.topic.number %}<small>#{{ user.current_session.topic.number }}</small>{% endif %}
                        </div>
                        {% if user.current_session.topic.description %}<p class="mb-1">Topic
                          Description: {{ user.current_session.topic.description }}
                          {{ user.current_session.topic.narrative|default_if_none:"" }}
                        </p>{% endif %}
                    </div>
                </div>
                <form method="POST" action="{% url 'core:home' %} " enctype="multipart/form-data">
                  {% csrf_token %}
                  {% crispy form_pre_task %}
                </form>
            </div>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">
          Cancel
        </button>
      </div>
    </div>
  </div>
</div>

web/Web/web/templates/modals/session_details_modal.html
<div class="modal" id="sessionModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header pb-0">
        <div class="modal-title text-primary d-flex flex-grow-1 ">
          <div class="d-flex flex-column flex-grow-1 ">
          <h5 class="text-primary">Session Details</h5>
          <h6 class="text-secondary" id="sessionModalTitle"></h6>
          <h6 class="text-muted small sessionModalDetails d-none">Created <span id="session_created_at"></span></h6>
          </div>



        </div>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="sessionModalBody">
        <div class="alert alert-danger d-none" id="sessionModalError"></div>

        <div class="center-text mt-3" id="sessionModalSpinner">
          <div class="spinner-border text-secondary" role="status">
            <span class="sr-only">Loading...</span>
          </div>
        </div>

        <div id="sessionModalDetails" class="sessionModalDetails d-none">
          <div class="tab-content">
            <div class="tab-pane show active" id="pills-details" role="tabpanel">
              <p class="mb-1">
                <h6 class="text-secondary">Description</h6>
              <p id="session_description"></p>
              </p>
              <p class="mb-1">
                <h6 class="text-secondary">Narrative</h6>
              <p id="session_narrative"></p>
              </p>
              <p class="mb-1">
                <h6 class="text-secondary d-inline">Seed query: </h6> <span id="session_seed_query"></span>
              </p>
              <p class="mb-1">
                <h6 class="text-secondary d-inline">Strategy:</h6> <span id="session_strategy"></span>
              </p>
              <p class="mb-1">
                <h6 class="text-secondary d-inline">Effort (max judgments):</h6> <span id="session_effort"></span>
              </p>

              <div class="row">
                <div class="col-md-5 col-sm-5 mx-auto center-text">
                  <canvas id="piechart" width="200" height="200" class="mt-2"></canvas>
                </div>
              </div>
            </div>
            <div class="tab-pane" id="pills-shared-with" role="tabpanel">
              <form action="" method="POST">
              {% csrf_token %}
              <div id="sessionSharedWithList">
                <!-- List of users will be displayed here using template from function templateSharedToUser -->
              </div>
              </form>
            </div>
          </div>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">
          Close
        </button>
      </div>
    </div>
  </div>
</div>

web/Web/web/templates/modals/share_session_modal.html
{% load crispy_forms_tags %}

<div class="modal" id="shareSessionModal" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="d-flex flex-row">
          <div class="d-flex flex-column flex-grow-1 ">
            <h5 class="text-primary">Share Session</h5>
            <h6 class="text-secondary" id="shareSessionModalTitle">{{ user.current_session.topic.title }}</h6>
            <h6 class="text-muted small">Sharing a session with other users enables collaboration in finding relevant
            documents.</h6>
            </div>
        </div>

        <button type="button" class="close" data-dismiss="modal"
                aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="{% url 'core:share_session' %}" method="POST">
        <div class="modal-body">
          {% csrf_token %}
          {{ share_session_form|crispy }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary"
                  data-dismiss="modal">Close
          </button>
          <button type="submit" class="btn btn-outline-secondary"
                  name="share_sessionid" value="{{ user.current_session.uuid }}"
                  id="shareSessionModalShareButton">Share
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

web/Web/web/templates/modals/task_finished_modal.html
<div class="modal" id="TaskFinishedModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-primary">Task Completed!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
     {% if experiment_completed %}
        <div class="modal-body">
            <p>Congratulations! You have completed all the tasks. Please visit the homepage to
              complete the post-experiment questionnaire.</p>
         </div>
        <div class="modal-footer">
            <a class="btn btn-outline-primary" data-dismiss="modal" href="{% url 'core:home'%}">Go to homepage</a>
        </div>
      {% else %}
        <div class="modal-body">
             <p>Congratulations! You have completed the task. Please visit the homepage to
              complete the post-task questionnaire. Your next task will start as soon as you complete the questionnaire.
             </p>
        </div>
        <div class="modal-footer">
            <a class="btn btn-outline-primary" href="{% url 'core:home'%}">Go to homepage</a>
        </div>
      {% endif %}
    </div>
  </div>
</div>

web/Web/web/templates/modals/time_spent_modal.html
<div class="modal" id="TimeSpentModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-primary">Time Spent</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>You have spent <span id="time_worked_div">{{ time_worked }}</span> on task. Remember,
        your time
        is only
          counted while you
          are actively working on the task. If you are not working on the task, the timer is paused.</p>
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

web/Web/web/templates/modals/topic_details_modal.html
<div class="modal" id="TopicDetailsModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-primary">Topic Details</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class=" border-0 p-0">
            <div class="d-flex w-100 justify-content-between">
              <p class="mb-2">Topic title: {{ user.current_session.topic.title }}</p>
              {% if user.current_session.topic.number %}<small>#{{ user.current_session.topic.number }}</small>{% endif %}
            </div>
            {% if user.current_session.topic.description %}<p class="mb-1">Topic
              Description: {{ user.current_session.topic.description }}
              {{ user.current_session.topic.narrative|default_if_none:"" }}
            </p>{% endif %}
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>