web/Web/config/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
import notifications.urls

from config.logger import LoggerView

urlpatterns = [
    path('', include('web.core.urls', namespace='core')),
    path('about/', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    path('users/', include('web.users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),

    # Notifications
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

    # Custom urls includes go here
    path('discovery/', include('web.CAL.urls', namespace='CAL')),
    path('search/', include('web.search.urls', namespace='search')),
    path('topic/', include('web.topic.urls', namespace='topic')),
    path('judgment/', include('web.judgment.urls', namespace='judgment')),
    path('review/', include('web.review.urls', namespace='review')),

    # Logger
    path(r'logger/', LoggerView.as_view(), name='logger'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

web/Web/web/topic/urls.py
from django.urls.conf import path
from django.urls.conf import re_path

from web.topic import views

app_name = "topic"

urlpatterns = [
    re_path(r'^(?P<pk>[\w.@+-]+)$', views.TopicView.as_view(), name='detail'),
    path('create/', views.TopicCreateView.as_view(), name='create'),
    path('list/', views.TopicListView.as_view(), name='list'),
    path('activate/', views.TopicActivateView.as_view(), name='activate'),
    path('delete/', views.TopicDeleteView.as_view(), name='delete'),
]

web/Web/web/topic/models.py
from django.db import models


class Topic(models.Model):
    number = models.PositiveIntegerField(null=True,
                                         blank=True)
    title = models.CharField(null=False,
                             blank=False,
                             max_length=512)
    seed_query = models.CharField(null=False,
                                  blank=False,
                                  max_length=512)
    description = models.TextField(null=True,
                                   blank=True)
    display_description = models.TextField(null=True,
                                           blank=True)
    narrative = models.TextField(null=True,
                                 blank=True)

    created_at = models.DateTimeField(auto_now_add=True,
                                      editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return "{} {}".format(self.number, self.title)

    def __str__(self):
        return f'{self.title}-{self.seed_query}'

web/Web/web/topic/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms

from web.topic.models import Topic


class TopicForm(forms.ModelForm):
    """
    Form for creating a new Topic

    """
    submit_name = 'submit-topic-form'

    class Meta:
        model = Topic
        fields = ['title', 'number', 'seed_query', 'description']

    def __init__(self, *args, **kwargs):
        super(TopicForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['seed_query'].widget.attrs['readonly'] = True
            self.fields['number'].widget.attrs['readonly'] = True

        self.helper = FormHelper(self)
        self.helper.layout.append(
            Submit(self.submit_name, u'Submit',
                   css_class='btn btn-primary')
        )

web/Web/web/topic/views.py
import logging

from braces.views import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from web.CAL.exceptions import CALError
from web.interfaces.CAL import functions as CALFunctions
from web.topic.forms import TopicForm
from web.topic.models import Topic

logger = logging.getLogger(__name__)


class TopicView(LoginRequiredMixin, generic.DetailView):
    model = Topic
    template_name = "topic/details.html"
    object = None

    def get_context_data(self, **kwargs):
        context = {
            "form": TopicForm(instance=self.request.user.current_session.topic)
        }

        return context

    def get_success_url(self):
        return reverse_lazy('topic:detail', kwargs={'pk': self.object.id})

    def post(self, request, *args, **kwargs):
        unmodified_object = self.get_object()
        self.object = self.get_object()
        context = self.get_context_data()

        if 'submit-topic-form' in request.POST:
            form = TopicForm(request.POST,
                             instance=self.object)
            context['form'] = form
            if form.is_valid():
                j = form.save(commit=False)
                j.save()
                messages.add_message(request,
                                     messages.SUCCESS,
                                     'Your topic has been updated.')
            else:
                context['object'] = unmodified_object
                return render(request,
                              template_name=self.template_name,
                              context=context
                              )

        return HttpResponseRedirect(self.get_success_url())


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    template_name = "topic/create.html"
    form_class = TopicForm
    object = None

    def get_success_url(self):
        return reverse_lazy('topic:list')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.username = self.request.user

        try:
            CALFunctions.add_session(str(self.object.uuid),
                                     self.object.topic.seed_query,
                                     self.object.strategy)
            self.object.save()
            messages.add_message(self.request,
                                 messages.SUCCESS,
                                 'Your topic has been created but it\'s not active. '
                                 'Activate it to start working under it')
        except CALError as e:
            messages.add_message(self.request,
                                 messages.ERROR,
                                 'Failed to create session. CAL backend failed to add  '
                                 'session')

        return HttpResponseRedirect(self.get_success_url())


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    template_name = "topic/list.html"

    def get_queryset(self):
        return super(TopicListView, self).get_queryset().filter(username=self.request.user)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.username = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class TopicActivateView(LoginRequiredMixin, generic.DetailView):
    model = Topic

    def get_success_url(self):
        return reverse_lazy('topic:list')

    def post(self, request, *args, **kwargs):
        topic_id = request.POST.get("topic_id")
        topic = Topic.objects.get(id=topic_id, username=request.user)
        request.user.current_session.topic = topic
        request.user.save()
        messages.add_message(request,
                             messages.SUCCESS,
                             'Your active topic has been updated.')
        return HttpResponseRedirect(self.get_success_url())


class TopicDeleteView(LoginRequiredMixin, generic.DetailView):
    model = Topic

    def get_success_url(self):
        return reverse_lazy('topic:list')

    def post(self, request, *args, **kwargs):
        topic_id = request.POST.get("topic_id")
        topic = Topic.objects.get(id=topic_id, username=request.user)
        topic.delete()
        messages.add_message(request,
                             messages.SUCCESS,
                             'Your topic has been deleted.')
        return HttpResponseRedirect(self.get_success_url())

web/Web/web/topic/templates/topic/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block pagetitle %}Topic create{% endblock %}

{% block main %}
<h3 class="text-primary">Add topic</h3>
<hr>
<div class="row top-bottom-margin">
    <div class="col-md-12">
        <form method="POST">
            {% csrf_token %}
            {% crispy form %}
        </form>
    </div>
</div>
{% endblock %}

web/Web/web/topic/templates/topic/details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block pagetitle %}Topic detail{% endblock %}

{% block main %}
<div class="row">
    <div class="col-md-8">
        <h3 class="text-primary">Your current topic</h3>
    </div>
    <div class="col-md-4">
        <a  href="{% url 'topic:list' %}" class="btn btn-primary btn-outline-primary">List created topics</a>
        <a  href="{% url 'topic:create' %}" class="btn btn-primary btn-outline-primary">Add new topic</a>
    </div>
</div>
<hr>
<div class="row top-bottom-margin">
    <div class="col-md-12">
        <form method="POST">
            {% csrf_token %}
            {% crispy form %}
        </form>
    </div>
</div>
{% endblock %}

web/Web/web/topic/templates/topic/list.html
{% extends 'base.html' %}

{% block pagetitle %}Topics list{% endblock %}

{% block main %}
<h3 class="text-primary">Current active topic</h3>

{% if user.current_session.topic %}
<div class="card top-margin">
    <div class="card-block">
        <a href="{% url 'topic:detail' pk=user.current_session.topic.id %}">
            <div class="row">
                <div class="col-md-2 text-primary">
                    {{ user.current_session.topic.title }}
                </div>
                <div class="col-md-8 gray-text">
                    {{ user.current_session.topic.seed_query }}
                </div>
                <div class="col-md-2">
                    <button type="submit" name="topic_id" value="{{ user.current_session.topic.topic.id }}" class="btn btn-primary disabled">Activated <small>(current)</small></button>
                </div>
            </div>
        </a>
    </div>
</div>
{% endif %}

<div class="row extra-top-margin">
    <div class="col-md-10">
        <h3 class="text-primary">Your created topics</h3>
    </div>
    <div class="col-md-2">
        <a  href="{% url 'topic:create' %}" class="btn btn-outline-primary">Add new topic</a>
    </div>
</div>

{% for topic in object_list %}
{% if topic == user.current_session.topic %}{% else %}
<div class="card top-margin">
    <div class="card-block">
        <div class="row">
            <div class="col-md-2 text-primary">
                {{ topic.title }}
            </div>
            <div class="col-md-7 gray-text">
                {{ topic.seed_query }}
            </div>
            <div class="col-md-3" style="display: inherit">
                <form method="POST" action="{% url 'topic:delete' %}">
                    {% csrf_token %}
                    <button type="submit" name="topic_id" value="{{ topic.id }}" class="btn btn-danger">Delete</button>
                </form>
                <form class="left-margin" method="POST" action="{% url 'topic:activate' %}">
                    {% csrf_token %}
                    <button type="submit" name="topic_id" value="{{ topic.id }}" class="btn btn-success">Activate</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endfor %}

{% endblock %}