web/Web/config/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
import notifications.urls

from config.logger import LoggerView

urlpatterns = [
    path('', include('web.core.urls', namespace='core')),
    path('about/', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    path('users/', include('web.users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),

    # Notifications
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

    # Custom urls includes go here
    path('discovery/', include('web.CAL.urls', namespace='CAL')),
    path('search/', include('web.search.urls', namespace='search')),
    path('topic/', include('web.topic.urls', namespace='topic')),
    path('judgment/', include('web.judgment.urls', namespace='judgment')),
    path('review/', include('web.review.urls', namespace='review')),

    # Logger
    path(r'logger/', LoggerView.as_view(), name='logger'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

web/Web/web/CAL/urls.py
from django.urls import path

from web.CAL import views

app_name = "CAL"

urlpatterns = [
    path('', views.CALHomePageView.as_view(),
         name='main'),

    # Ajax views
    path('post_log/', views.CALMessageAJAXView.as_view(),
         name='post_log_msg'),
    path('get_docs/', views.DocAJAXView.as_view(),
         name='get_docs'),
    path('get_docs_ids/', views.DocAJAXView.as_view(),
         name='get_docs_ids'),
    path('get_scal_info/', views.SCALInfoView.as_view(),
         name='get_scal_info'),
    path('ds_logging/', views.DSLoggingView.as_view(),
         name='ds_logging'),
]

web/Web/web/core/urls.py
from django.urls import path

from web.core import views
from web.core import practice_views

app_name = "core"

urlpatterns = [
    path('', views.Home.as_view(),
         name='home'),
    path('sessions/', views.SessionListView.as_view(),
         name='sessions'),

    # Practice views
    path('practice/', practice_views.PracticeView.as_view(),
         name='practice'),
    path('practice_complete/', practice_views.PracticeCompleteView.as_view(),
         name='practice_complete'),

    # Ajax views
    path('get_single_doc/', views.GetDocAJAXView.as_view(),
         name='get_single_doc'),

    path('get_session_details/', views.SessionDetailsAJAXView.as_view(),
         name='get_session_details'),
    path('share_session_view/', views.SessionShareView.as_view(),
         name='share_session'),

    path('update_session_timer/', views.update_remote_session_timer, name='update_session_timer'),
    path('update_task_time/', views.update_task_time, name='update_task_time'),
]

web/Web/web/judgment/urls.py
from django.urls import path
from django.urls import re_path

from web.judgment import views

app_name = "judgment"

urlpatterns = [

    path('view/', views.JudgmentsView.as_view(),
         name='view'),

    # Ajax views
    path('post_judgment/', views.JudgmentAJAXView.as_view(),
         name='post_judgment'),
    path('post_nojudgment/', views.NoJudgmentAJAXView.as_view(),
         name='post_nojudgment'),
    re_path(r'^get_latest/(?P<number_of_docs_to_show>\d+)/$',
            views.GetLatestAJAXView.as_view(),
            name='get_latest'),
    path('get_all/', views.GetAllAJAXView.as_view(),
         name='get_all'),
]

web/Web/web/judgment/forms.py
from crispy_forms.helper import FormHelper, Layout
from django import forms


class UploadForm(forms.Form):
    """
    Form for uploading judgments for current session

    """
    submit_name = 'upload-form'

    csv_file = forms.FileField(required=True,
                               label="CSV File",
                               widget=forms.FileInput)
    train_model = forms.BooleanField(
        required=False,
        label="Use judgments to train CAL model.",
        widget=forms.CheckboxInput
    )
    update_existing = forms.BooleanField(
        required=False,
        label="Update existing judgments"
    )

    def __init__(self, *args, **kwargs):
        super(UploadForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.use_custom_control = True
        self.helper.help_text_inline = True
        self.helper.form_tag = False

        self.helper.layout = Layout(
            'csv_file',
            'train_model',
            'update_existing',
        )


class UploadDebuggingJudgmentsForm(forms.Form):
    """
    Form for uploading debugging judgments for current session

    """
    submit_name = 'upload-debugging-form'

    debugging_csv_file = forms.FileField(required=True,
                                         label="CSV File",
                                         widget=forms.FileInput)

    def __init__(self, *args, **kwargs):
        super(UploadDebuggingJudgmentsForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.use_custom_control = True
        self.helper.help_text_inline = True
        self.helper.form_tag = False

        self.helper.layout = Layout(
            'debugging_csv_file',
        )

web/Web/web/judgment/views.py
import csv
import io
import itertools
import json
import logging
import traceback

from braces import views
from django.contrib import messages
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import StreamingHttpResponse
from django.urls import reverse_lazy
from django.views import generic
from interfaces.DocumentSnippetEngine import functions as DocEngine

from web.CAL.exceptions import CALError
from web.core.models import LogEvent, Session
from web.interfaces.CAL import functions as CALFunctions
from web.judgment.forms import UploadForm, UploadDebuggingJudgmentsForm
from web.judgment.models import Judgment, DebuggingJudgment


logger = logging.getLogger(__name__)


class JudgmentAJAXView(views.CsrfExemptMixin,
                       views.LoginRequiredMixin,
                       views.JsonRequestResponseMixin,
                       generic.View):
    require_json = False

    def render_timeout_request_response(self, error_dict=None):
        if error_dict is None:
            error_dict = self.error_response_dict
        json_context = json.dumps(
            error_dict,
            cls=self.json_encoder_class,
            **self.get_json_dumps_kwargs()
        ).encode('utf-8')
        return HttpResponse(
            json_context, content_type=self.get_content_type(), status=502)

    def post(self, request, *args, **kwargs):
        user = self.request.user
        current_session = self.request.user.current_session

        try:

            doc_id = self.request_json[u"doc_id"]
            doc_title = self.request_json[u"doc_title"]
            doc_CAL_snippet = self.request_json.get(u"doc_CAL_snippet", None)
            doc_search_snippet = self.request_json.get(u"doc_search_snippet", None)
            relevance = self.request_json.get(u"relevance", None)
            additional_judging_criteria = self.request_json.get(u"additional_judging_criteria", None)
            source = self.request_json[u"source"]
            method = self.request_json.get(u"method", None)
            query = self.request_json.get(u"query", None)
            client_time = self.request_json.get(u"client_time", None)
            historyItem = self.request_json.get(u"historyItem")
            search_query = self.request_json.get(u"search_query", None)
            ctrl_f_terms_input = self.request_json.get(u"ctrl_f_terms_input", None)
            found_ctrl_f_terms_in_title = self.request_json.get(u"found_ctrl_f_terms_in_title", None)
            found_ctrl_f_terms_in_summary = self.request_json.get(u"found_ctrl_f_terms_in_summary", None)
            found_ctrl_f_terms_in_full_doc = self.request_json.get(u"found_ctrl_f_terms_in_full_doc", None)
            current_docview_stack_size = self.request_json.get(u"current_docview_stack_size", None)
        except KeyError:
            error_dict = {u"message": u"POST input missing important fields"}

            return self.render_bad_request_response(error_dict)

        # Check if a judgment exists already, if so, update the db row.
        exists = Judgment.objects.filter(user=user,
                                         doc_id=doc_id,
                                         session=current_session)
        old_relevance = None

        if exists:
            exists = exists.first()
            old_relevance = exists.relevance
            exists.query = query
            exists.doc_title = doc_title
            if doc_CAL_snippet != "":
                exists.doc_CAL_snippet = doc_CAL_snippet
            if doc_search_snippet != "":
                exists.doc_search_snippet = doc_search_snippet
            if relevance is not None:
                exists.relevance = relevance
            if additional_judging_criteria is not None:
                exists.additional_judging_criteria = additional_judging_criteria
            exists.source = source
            exists.method = method
            exists.historyVerbose.append(historyItem)
            exists.search_query = search_query
            exists.ctrl_f_terms_input = ctrl_f_terms_input
            exists.found_ctrl_f_terms_in_title = found_ctrl_f_terms_in_title
            exists.found_ctrl_f_terms_in_summary = found_ctrl_f_terms_in_summary
            exists.found_ctrl_f_terms_in_full_doc = found_ctrl_f_terms_in_full_doc
            exists.save()

        else:
            Judgment.objects.create(
                user=user,
                doc_id=doc_id,
                doc_title=doc_title,
                doc_CAL_snippet=doc_CAL_snippet,
                doc_search_snippet=doc_search_snippet,
                session=current_session,
                query=query,
                relevance=relevance,
                additional_judging_criteria=additional_judging_criteria,
                source=source,
                method=method,
                historyVerbose=[historyItem],
                search_query=search_query,
                ctrl_f_terms_input=ctrl_f_terms_input,
                found_ctrl_f_terms_in_title=found_ctrl_f_terms_in_title,
                found_ctrl_f_terms_in_summary=found_ctrl_f_terms_in_summary,
                found_ctrl_f_terms_in_full_doc=found_ctrl_f_terms_in_full_doc
            )

        LogEvent.objects.create(
            user=self.request.user,
            session=current_session,
            action='JUDGMENT',
            data={
                'doc_id': doc_id,
                'relevance': relevance,
                'source': source,
                'old_relevance': old_relevance,
            }
        )

        total_session_timer = current_session.timespent

        total_positive_judgments_for_session = Judgment.objects.filter(
            user=user,
            session=current_session,
            relevance__in=(1, 2),
        ).count()

        context = {u"message": u"Your judgment on {} has been received!".format(doc_id),
                   u"is_max_judged_reached": False,
                   u"positive_judgements": total_positive_judgments_for_session,
                   u"is_positive_judgements_reached": total_positive_judgments_for_session == 5,
                   u"is_session_max_time_reached": current_session.max_time is not None and
                                                   total_session_timer >= current_session.max_time,
                   }


        error_message = None

        # This will take care of incomplete judgments (e.g. updating additional judging
        # criteria without making a final judgment on the document)
        if relevance is None:
            return self.render_json_response(context)

        is_from_cal = source == "CAL"
        # mark relevant documents as 1 to CAL.
        rel_CAL = -1 if relevance <= 0 else 1

        if rel_CAL == 0 and current_session.is_shared:
            # Check if someone else in the shared session has marked it as rel
            # if so, cant re-train CAL with this doc as non-relevant
            others_judged_as_rel = Judgment.objects.filter(
                session=current_session,
                relevance__lgt=0
            ).exclude(user=user).exists()
            if others_judged_as_rel:
                rel_CAL = 1

        if is_from_cal:
            context[u"next_docs"] = []

            try:
                next_batch, top_terms = CALFunctions.send_judgment(
                    current_session.uuid,
                    doc_id,
                    rel_CAL)
                if not next_batch:
                    return self.render_json_response(context)

                ret = {}
                next_batch_ids = []
                for docid_score_pair in next_batch:
                    doc_id, doc_score = docid_score_pair.rsplit(':', 1)
                    ret[doc_id] = doc_score
                    next_batch_ids.append(doc_id)

                doc_ids_hack = []
                for doc_id in next_batch_ids:
                    doc = {'doc_id': doc_id}
                    if '.' in doc_id:
                        doc['doc_id'], doc['para_id'] = doc_id.split('.')
                    doc_ids_hack.append(doc)
                seed_query = current_session.topic.seed_query
                if 'doc' in current_session.strategy:
                    documents = DocEngine.get_documents(next_batch_ids,
                                                        seed_query,
                                                        top_terms)
                else:
                    documents = DocEngine.get_documents_with_snippet(doc_ids_hack,
                                                                     seed_query,
                                                                     top_terms)

                # append debugging rel to documents
                for doc in documents:
                    doc["debugging_rel"] = -1
                    djudged = DebuggingJudgment.objects.filter(user=self.request.user,
                                                               doc_id=doc["doc_id"],
                                                               session=self.request.user.current_session)
                    if djudged.exists():
                        djudged = djudged.first()
                        doc["debugging_rel"] = djudged.relevance
                    else:
                        doc["debugging_rel"] = -1  # unjudged

                context[u"next_docs"] = documents
            except TimeoutError:
                context["CALFailedToReceiveJudgment"] = True
                error_dict = {u"message": u"Timeout error. "
                                          u"Please check status of servers."}
                return self.render_timeout_request_response(error_dict)
            except CALError as e:
                context["CALFailedToReceiveJudgment"] = True
                error_message = "CAL Exception: {}".format(str(e))
            except Exception as e:
                context["CALFailedToReceiveJudgment"] = True

web/Web/web/judgment/templates/judgment/judgments.html
{% extends 'core/home_base.html' %}
{% load static crispy_forms_tags  %}
{% block pagetitle %}Judgments{% endblock %}
{% block home-nav-judgments-extra-class %}border-bottom{% endblock %}

{% block home-main %}
<div class="row top-bottom-margin">
  <div class="col-md-9 order-2 order-md-1">
    <div class="card mb-2 border-0">
      <div class="card-block">
        <h2 class="text-dark mb-1">Judgments</h2>
        <span class="text-muted">Details judgments made for this session.</span>
        <div class="row extra-top-margin">
          <div class="col-md-12 table-responsive judgment_table p-3 small-radius">
            <table class="table judgment_table table-borderless table-hover small m-0">
              <thead>
              <tr>
                <th>Docno</th>
                <th>Document Title</th>
                <th>Judgment</th>
                <th>User</th>
              </tr>
              </thead>
              <tbody>
              {% for row in judgments %}
              <tr
                  id="doc_{{row.doc_id}}_card"
                  data-doc-id="{{ row.doc_id }}"
                  data-title="{{ row.doc_title|safe }}"
                  data-toggle="modal" data-target="#documentModal"
                  class="searchItemSelector"
                  style="cursor: pointer;"
              >
                <th scope="row">
                  <code><span class="text-primary small">{{ row.doc_id }}</span></code>
                </th>
                <td>{{ row.doc_title|truncatechars:100 }}</td>
                <td>
                  <span id="doc_{{row.doc_id}}_judgment_badge" class="badge
                  {% if row.relevance == 2 %}badge-highlyRelevant {% elif row.relevance == 1 %}badge-relevant{% else %}badge-nonRelevant{%endif%}">
                    {% if row.relevance == 2 %}Highly {% if main_judging_criteria_name %}{{ main_judging_criteria_name }}{% else %}Relevant{% endif %} {% elif row.relevance == 1 %}{% if main_judging_criteria_name %}{{ main_judging_criteria_name }}{% else %}Relevant{% endif %}{% else %}Non-{% if main_judging_criteria_name %}{{ main_judging_criteria_name }}{% else %}Relevant{% endif %}{%endif%}
                  </span>
                </td>
                <td>{{ row.user }}</td>
              </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

  </div>

  <div class="col-md-3 order-1 order-md-2 mb-3">
    <div class="card border-0 sticky-top" style="top: 73px; z-index: 0;">
      <div class="card-block">
        <h2 class="text-dark mb-4">Operations</h2>

        <a id="import_csv" href="#" class="btn btn-outline-primary btn-sm mb-3 btn-block" data-toggle="modal" data-target="#importModal">Import judgments</a>
        <a id="export_csv" href="#" class="btn btn-outline-primary btn-sm mb-3 btn-block" data-toggle="modal" data-target="#exportModal">Export to csv</a>
        {% if request.user.current_session.show_debugging_content %}
        <hr>
        <a id="debugging_csv" href="#" class="btn btn-outline-primary btn-sm mb-3 btn-block" data-toggle="modal" data-target="#debuggingModal">Import debugging judgments</a>
        {% endif %}

      </div>
    </div>
  </div>

  <!-- Import Modal -->
  <div class="modal" id="importModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <div class="d-flex flex-column flex-grow-1 ">
            <h5 class="modal-title text-primary">Import judgments</h5>
            <h6 class="text-muted">Please reformat your CSV file to have columns, <code>docno</code>, and <code>judgment</code>.</h6>
          </div>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form method="POST" enctype="multipart/form-data" id="import_csv_form" name="form_type" value="import_csv_form">
          <input name="form_id" value="import_csv_form" type="hidden"/>
          <div class="modal-body">
              <p>Example of accepted CSV file:</p>
                    <pre class="small text-muted">
                      docno,judgment
                      mydocid1,1,
                      mydocid2,0,
                      mydocid3,2</pre>

              {% csrf_token %}
              {% crispy upload_form %}

          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
            <button class="btn btn-outline-secondary" id="import_csv_button" type="submit">Upload</button>
          </div>
        </form>
      </div>
    </div>
  </div>


  <!-- Export Modal -->
  <div class="modal" id="exportModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <div class="d-flex flex-column flex-grow-1 ">
            <h5 class="modal-title text-primary">Export judgments</h5>
            <h6 class="text-muted">Judgments will be exported in csv format, with columns, <code>docno</code>, <code>judgment</code>, and <code>user</code>.</h6>
          </div>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form method="GET" id="export_csv_form">
          {% csrf_token %}
          <div class="modal-body">
              <p>Example of exported CSV file:</p>
                <pre class="small text-muted">
                  docno,judgment,user
                  mydocid1,1,myusername
                  mydocid2,0,myusername
                  mydocid3,2,myusername</pre>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
            <button class="btn btn-outline-secondary" id="export_csv_button" name="export_csv" value="export_csv" type="submit">Export to CSV</button>
          </div>
        </form>
      </div>
    </div>
  </div>

  {% if request.user.current_session.show_debugging_content %}
  <!-- Debugging Modal -->
  <div class="modal" id="debuggingModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <div class="d-flex flex-column flex-grow-1 ">
            <h5 class="modal-title text-primary">Debugging judgments</h5>
            <h6 class="text-muted">Judgments will be shown while interactively judging (if the document is judged).</h6>
            <h6 class="text-muted">Please reformat your CSV file to have columns, <code>docno</code>, and <code>judgment</code>.</h6>

          </div>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form method="POST" enctype="multipart/form-data" id="import_debugging_judgements_csv_form" name="form_type" value="import_debugging_judgements_csv_form">
          <input name="form_id" value="import_debugging_judgements_csv_form" type="hidden"/>

          <div class="modal-body">
              <p>Example of accepted CSV file:</p>
                    <pre class="small text-muted">
                      docno,judgment
                      mydocid1,1,
                      mydocid2,0,
                      mydocid3,2</pre>

              {% csrf_token %}
              {% crispy upload_debug_form %}

          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
            <button class="btn btn-outline-secondary" id="import_review_csv_button" type="submit">Upload</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  {% endif %}

  <!-- Document modal -->
  {% include 'modals/document_modal.html' %}
  <!-- Judging criteria modal -->
  {% include 'modals/additional_judging_criteria_modal.html' %}
  <!-- Discovery failed to receive judgment toast -->
  {% include 'toasts/discovery_failed_to_receive_judgment.html' %}

</div>

{% endblock %}

{% block extra_scripts %}
    <script src="https://unpkg.com/runtime-memcache@2.0.0"></script>
    <script src="{% static 'js/moment.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <script src="{% static 'js/document-viewer.js' %}"></script>
    <script src="{% static 'js/highlight.js' %}"></script>

    <script>

        var dv = new docView();
        dv.init({
          username: '{{ request.user }}',
          singleDocumentMode: true,
          judgingSourceName: "judgmentsPage",
          searchMode: true,
          getDocumentsToJudgeURL: '{% url 'CAL:get_docs' %}',
          getPrevDocumentsJudgedURL: '{% url 'judgment:get_latest' number_of_docs_to_show=50 %}',
          getDocumentIDsToJudgeURL: '{% url 'CAL:get_docs_ids' %}',
          sendDocumentJudgmentURL: '{% url 'judgment:post_judgment' %}',
          getDocumentURL: '{% url 'core:get_single_doc' %}?docid=',
          fetchPreviouslyJudgedDocsOnInit: false,
          mainJudgingCriteriaName: '{% if main_judging_criteria_name %}{{ main_judging_criteria_name }}{% else %}Relevant{% endif %}',
          csrfmiddlewaretoken: "{{ csrf_token }}",

          afterDocumentJudge: function(docid, rel) {
            // update document indicator in SERP
            let newColor = "";
            let relText = "";
            switch (rel) {
              case 0:
                newColor = "badge-nonRelevant"; relText = "Non-{% if main_judging_criteria_name %}{{ main_judging_criteria_name }}{% else %}Relevant{% endif %}"
                break;
              case 1:
                newColor = "badge-relevant"; relText = "{% if main_judging_criteria_name %}{{ main_judging_criteria_name }}{% else %}Relevant{% endif %}";
                break;
              case 2:
                newColor = "badge-highlyRelevant"; relText = "Highly {% if main_judging_criteria_name %}{{ main_judging_criteria_name }}{% else %}Relevant{% endif %}";
                break;
            }
            $(`#doc_${docid}_judgment_badge`).attr('class', `badge ${newColor}`);
            $(`#doc_${docid}_judgment_badge`).text(relText);
            console.log(`badge ${newColor}`);
          },

          afterDocumentLoad: function (docid) {
            // Perform keyword search if necessary
            searchForKeyword();
          },

          afterCALFailedToReceiveJudgment: function(docid, rel) {
            $('#toast_CALFailedToReceiveJudgment').toast('dispose');
            $(".CALFailedToReceiveJudgmentSpinner").removeClass("d-none");
            $("#CALFailedToReceiveJudgment_toast_body").addClass("d-none");
            $("#toast_CALFailedToReceiveJudgment_docid").html(docid);
            setInterval(function(){
              $("#CALFailedToReceiveJudgment_toast_body").removeClass("d-none");
              $(".CALFailedToReceiveJudgmentSpinner").addClass("d-none");
            },500);
            $('#toast_CALFailedToReceiveJudgment').toast('show');
          }
        });

    </script>
{% endblock %}